[MISSING_PAGE_FAIL:1]

향상들은 상태-공간의 광범위하고 깊은 탐색을 둘 다 제공할 필요가 있으며, 따라서 네트워크 프로토콜 구현들의 높은 소스 코드 커버리지를 초래한다. 본 연구의 예비 연구는 네트워크 프로토콜 구현을 검증하기 위한 퍼징 및 심볼 실행에 대한 자세한 조사 및 분류를 제공한다. 따라서 우리는 두 가지 중요한 기여를 합니다. 먼저, 네트워크 프로토콜 구현에서 자동으로 높은 커버리지 테스트 패킷을 생성하기 위해 퍼징과 결합된 심볼릭 실행을 사용하는 새로운 검증 기법을 설명한다. 우리는 네트워크 프로토콜의 구현이 충돌할 수 있는 잘못된 메모리 액세스 또는 제로 분할과 같은 다양한 일반적인 구현 오류를 감지한다. 네트워크 프로토콜의 초기 탐색을 위해 퍼징을 사용하고, 심볼릭 실행을 적용하여 네트워크 프로토콜 구현을 위한 높은 커버리지 테스트 패킷을 자동으로 생성한다. 둘째, 본 논문의 실험 결과는 ESBMC(Fuzzing et al., 2019)가 네트워크 프로토콜의 보안 취약점을 탐지하기 위해 더 발전할 수 있음을 보여준다. 특히, ESBMC는 Mapzcheck(Marcus et al., 2019), KLEE(Kaley et al., 2019), SPIKE(Barcus et al., 2019)와 같은 기존의 다른 도구들보다 FTP 구현을 목표로 하는 보안 취약점을 빠르게 탐지할 수 있었다.

## 2. Preliminaries

### Network Protocol

네트워크는 통신 기술들과 상호 연결되고 정보의 교환을 허용하는 엔티티들의 그룹으로 정의될 수 있다(Bradbury et al., 2017). 통신하는 엔티티들은 정보를 교환하기 위한 동의가 필요하며, 이러한 동의는 _네트워크 프로토콜_이라고 알려져 있다. 이러한 엔터티가 교환하는 메시지는 _패킷_ 이라고 합니다. 패킷의 시퀀스를 _패킷 스트림_ 이라고 합니다. 방법, 동작 및 패킷 포맷과 관련된 정보는 네트워크 프로토콜을 설계할 때 문서에서 설명된다(Marcus et al., 2019). 이들 문서는 프로토콜 구현의 개발자에 의해 일상적으로 참조되는 _프로토콜 사양_을 형성한다. 네트워크 프로토콜의 구현은 UNIX 및 기타 운영 체제에서 _네트워크 데몬_ 이라고 합니다. 프로토콜 \(P\)의 요구 사항이 지정되면, 이러한 요구 사항은 프로토콜 사양 \(S\)에 기술되고, 사양은 \(I\)에 구현된다. 예를 들어, 파일 전송 프로토콜(FTP)은 컴퓨터 네트워크 상의 클라이언트와 서버 사이의 컴퓨터 파일의 전송을 위해 사용되는 표준 네트워크 프로토콜(Kleiner 등, 2017); 프로토콜 사양을 형성하는 여러 RFC(Request For Comments) 문서에 기술되어 있다. FileZilla(Windows) 및 Pure-FTPd(Unix)와 같은 명세서의 여러 구현이 존재한다. FTP는 파일 교환을 위해 (TCP/IP) 네트워크에서 사용되는 애플리케이션 레벨 프로토콜이다. FTP는 다음과 같이 구현된다. 먼저 클라이언트는 21번 포트를 사용하여 서버에 연결합니다. 클라이언트 요청은 이 소켓을 사용하여 ASCII에서 전송됩니다. 클라이언트가 데이터 전송을 요청할 때 서버와 함께 포트 20에 새 소켓이 열립니다. 클라이언트 요청은 대부분 4자 메시지 유형에 이어 실제 메시지로 구성됩니다. 서버 응답은 ASCII에 있으며, 여기서 처음 세 자리는 옵션 메시지가 뒤따르는 상태 코드에 대응한다. 우리는 프로토타입을 평가하기 위해 FTP 구현을 사례 연구로 사용한다.

### Fuzzing

퍼징은 소프트웨어 시스템의 취약점을 악용하기 위한 소프트웨어 테스팅 기법이다(Kleiner et al., 2017). 퍼징은 타겟 네트워크 프로토콜에 대한 랜덤 또는 준-랜덤 입력들을 준비한다. 중요한 보안 결함은 프로그램 입력이 적절하게 체크되지 않기 때문에 가장 자주 발생한다(Fuzzing et al., 2019). 이러한 입력들은 무작위적이기 때문에, 타겟 네트워크 프로토콜에서의 그들의 예상치 못한 부적절한 출현은 매우 개연성이 높다. 대상 네트워크 프로토콜이 이러한 부적절한 입력을 거부하지 않으면 퍼즈 테스트 중에 중단되거나 중단됩니다. 퍼징은 네트워크 프로토콜에서 보안 취약점을 찾기 위한 빠르고 비용 효율적인 방법이다. 퍼징을 견딜 수 없는 소프트웨어 시스템은 잠재적으로 보안 허점으로 이어질 수 있다. 예를 들어, FTP 프로토콜에서 Wireshark와 같은 네트워크 분석기는 서버/클라이언트 세션 간에 기록된 대화로부터 네트워크 프로토콜 구현의 사양을 추출한다. 네트워크 프로토콜 사양이 추출되면 퍼징 엔진에는 확장 가능한 퍼징 함수 목록이 로드됩니다. 처음에, 퍼징 엔진은 자신의 상태를 프로토콜의 루트로 설정한다. 그런 다음 입력 트래픽을 모니터링하여 적절한 전환을 수행하고 퍼징 기능을 적용합니다.

### Symbolic Execution

상징 실행은 프로그램 동작을 분석하고 테스트 케이스를 생성하여 보안 취약점을 찾는 데 널리 사용되고 있다(Fuzzing et al., 2019). 구체적 입력값 대신 기호적 입력값을 사용하는 것이 기호 실행의 주요 개념이다. 이 방법은 경로를 기호적 제약조건으로 취급하고 제약조건을 풀어서 구체적인 입력을 테스트 케이스로 출력한다. 네트워크 프로토콜 측면에서, 우리는 타겟 네트워크 프로토콜 구현의 프로토콜 사양으로부터 메시지 포맷을 추출한다. 그리고, 이러한 메시지 포맷을 이용하여 구체적인 패킷을 구성하는데, 이 패킷의 ID 필드를 심볼릭 값으로 표시하여 심볼릭 패킷을 구성한다. 이후 심볼릭 실행 엔진을 호출하여 경로 기반 심볼릭 실행과 BMC 두 가지 접근 방법을 사용하여 프로토콜 프로그램의 가능한 경로를 탐색한다.

### 네트워크 프로토콜 확인에 대한 문제

네트워크 프로토콜을 확인하려면 많은 문제가 있습니다. 첫째, 네트워크 프로토콜 크기는 서로 다른 통신 엔티티를 수반하기 때문에 크고 복잡하다. 둘째, 테스트와 검증은 오랜 기간의 동작 후에야 많은 오류가 나타나는 긴 과정이다. 경로 폭발을 피하는 것은 상징적 실행 엔진을 사용할 때 직면할 수 있는 가장 어려운 도전 중 하나이다. 고려되는 실행 경로의 가능한 수는 너무 커서, 프로그램 상태-공간의 작은 부분만이 탐색된다. 마지막으로 가상 환경에서 프로토콜을 테스트하는 것은 실제 환경에서 테스트하는 것과 같지 않다. 따라서 실제 환경에서 네트워크 프로토콜의 취약점을 탐지하는 것은 도전 과제이며, 이는 행동 정확성을 보장하기 위한 전문화된 검증 접근법을 필요로 한다.

## 3. 네트워크 프로토콜 구현에서 취약성 찾기

네트워크 프로토콜 구현은 종종 개발자 실수로 인해 취약성이 발생하기 쉬운데, 이러한 취약성은 실행중인 프로그램이 메모리 버퍼 외부에 데이터를 쓰려고 시도하는 상황(Barcus et al., 2019); 프로그래머가 힙에서 메모리를 만들고 삭제를 잊어버릴 때 발생하는 메모리 누출(Zhu et al., 2019); 공격자가 정당한 사용자가 특정 컴퓨터 시스템, 장치, 서비스 또는 기타 IT 리소스에 액세스하는 것을 방지할 때 발생하는 보안 이벤트인 서비스 거부 공격(DoS)을 포함한다(Kang et al., 2017). 일례로서, Cisco IOS XE Software Release 16.6.1 및 16.6.2의 CDP(Cisco Discovery Protocol) 모듈에서의 취약성은 인증되지 않은 인접한 공격자가 메모리 누출을 야기할 수 있고, 이는 DoS 조건으로 이어질 수 있다(Kang et al., 2017).

### _FuSeBMC for detect security vulnerabilities

퍼징과 상징적 실행을 결합한 도구를 검색한 결과, 단 하나의 유망한 도구인 Driller(Kang et al., 2017)를 발견하였다. 퍼징과 심볼릭 실행을 결합한다고 주장하는 다른 방법들이 존재하지만, 우리는 이용가능한 툴 구현을 발견하지 못했다(Kang et al., 2017). 소프트웨어 검증 및 테스트에 대한 현재 지식을 감안할 때 네트워크 프로토콜 분야에서 개발된 도구는 없으며, 네트워크에서 패킷을 처리해야 하는 것은 두 기술을 통합하는 도구에서 해결하지 못한 과제 중 하나이다. 그러나 두 기술을 결합하지 않는 일부 도구는 경로 폭발이나 낮은 커버리지와 같은 몇 가지 문제에 직면했다. 따라서 본 논문에서는 퍼징과 심볼릭 실행을 이용한 네트워크 프로토콜 구현에서 보안 취약점을 탐지하기 위한 새로운 접근법인 _FuSeBMC_를 제안한다. 주요 아이디어는 초기에 상태-공간을 탐색하기 위해 퍼징을 사용하여 테스트 입력 패킷들의 세트를 생성하는 것이다. 이러한 테스트 입력은 심볼릭 실행 및 BMC 엔진이 퍼징이 도달하지 못한 부분을 탐색하도록 안내할 것이다. 즉, 스캐닝 과정을 합법화하고 코드 폭발 등의 문제를 피할 수 있을 것이다. 그런 다음, 심볼릭 실행과 BMC를 사용하여 높은 코드 커버리지를 달성하고 구현에 대해 다시 재생하여 프로토콜 사양에서 파생된 규칙의 잠재적인 위반을 관찰한다. 우리는 목표 구현의 상태 공간에 대한 광범위하고 심층적인 탐색을 달성하는 탐색 방법을 고안한다.

우리의 프로토타입은 그림 1에 나와 있다. 네트워크 프로토콜 구현을 검증하기 위한 다섯 가지 단계가 있다. 먼저 프로토콜 명세 분석기는 구체적인 패킷을 생성한다. 여기서는 Wireshark (Wiershaw, 2017)를 사용 하 여 클라이언트와 FTP 서버 간에 전송 되는 패킷을 캡처 합니다. 둘째, 프로토타입은 초기 테스트 케이스 및 유전자 돌연변이를 사용하여 새로운 테스트 케이스를 생성하는 도구인 미국 퍼지(AFL)(Zhou et al., 2017)를 사용한다. AFL은 표준 입력 또는 파일에서 입력을 받아들이는 대상 소프트웨어와 함께 작동합니다. 우리는 기능을 탐색하기 위한 소프트웨어를 퍼즈합니다. 그런 다음 퍼저에 의해 달성된 함수 커버리지를 계산한다. 셋째, 입력 패킷을 너무 많은 경로를 초래하는 심볼릭 패킷으로 표시하며, 이러한 경로들은 대부분 구현에 의해 폐기되는 유효하지 않은 패킷을 지칭하기 때문에 코드 커버리지를 증가시키지 않는다. 통상적으로 네트워크 패킷은 패킷 헤더의 일부인 다수의 필드들로 구성된다. 대부분의 프로토콜 구현들은 이러한 필드들을 처리하기 위한 로직을 포함한다. 따라서 _FuSeBMC_ 는 전체 입력 패킷 대신 이러한 필드를 기호 변수로 사용 합니다. 넷째, 경로 기반 심볼릭 실행과 BMC를 사용하여 퍼저가 탐지한 함수에 도달한다. 퍼저를 사용한 초기 탐색 단계 때문에 심볼릭 실행 엔진은 빠르게 도달할 수 있는 함수를 제외할 수 있게 되어 복잡하고 깊은 함수에 더 많은 시간을 할당할 수 있다. 마지막으로 심볼릭 마커는 패킷의 일부 바이트를 심볼릭 값으로 표시하여 콘크리트 패킷을 심볼릭 패킷으로 변환한다.

우리의 _FuSeBMC_ 프로토타입은 Map2Check (Kang et al., 2017) 위에 퍼징과 결합된 경로 기반 기호 실행 엔진으로 빌드되고 최신 BMC 엔진으로 ESBMC (Kang et al., 2018)에 빌드됩니다. 두 도구 모두 네트워크 프로토콜 소프트웨어의 모든 프로그램 경로를 탐색하고 메모리 모니터 모듈이 충돌을 보고하고 기록하는 동안 구체적인 패킷을 생성한다. 예를 들어, 사용자가 플래그 필드를 심볼릭으로 표시하라는 지시를 제공하는 경우, 우리의 프로토타입은 패킷 내의 이 필드의 콘크리트 값을 심볼릭 값으로 대체하면서 다른 필드들을 콘크리트로 유지한다. 따라서, _FuSeBMC_는 서로 다른 플래그 값을 갖는 다양한 입력 패킷에 대응하는 가능한 실행 경로를 탐색한다. 각 실행 경로의 끝에는 주어진 경로에 대한 구체적인 테스트 패킷을 디스크에 저장한다.

## 4. 실험 평가

### Benchmark 및 Setup

우리는 _FuSeBMC_를 설계했을 때 프로토타입에서 유지할 두 가지 주요 기준을 정의했다. 첫째, 네트워크 프로토콜 구현들을 그들의 프로토콜 사양들에 대해 검증함으로써 평가될 수 있는 버그들을 검출하는 능력. 둘째, 기존 접근법에 비해 보안 취약점을 찾기 위한 검증 시간이 짧다. C 프로그래밍 언어로 작성된 FTP(Simple File Transfer Protocol)와 보안 취약점이 있는 것으로 알려진 C로 작성된 서버(Vulnserver)에 대한 실험을 수행하였다. 이 두 개의 C 프로그램은 FTP 프로토콜의 간단한 구현이지만 처음에 제안된 검증 방법의 주요 요소를 평가할 수 있다. 또한, 취약점 탐지의 효과를 비교하기 위해 프로토콜 구현을 위한 세대 퍼저를 기반으로 하는 SPIKE(Bauer et al., 2017)와 방법을 비교하였다. 실험에서 우리는 "버퍼 오버플로"와 "산술 오버플로"의 두 가지 속성을 고려했다. 실험은 두 개의 머신, 즉 _호스트_ 머신과 _게스트_ 머신을 호스팅하여 수행되었다. 호스트 머신은 16GB 메모리를 갖는 Intel Core i7 2.9 GHz CPU를 포함하고 있으며, Ubuntu 14.04를 실행하고 있었다. 게스트 머신은 Windows 10을 실행하고 있었다. 도구들은 Ubuntu 14.04 시스템을 실행하고 있었고, 퍼징 도구 SPIKE는 가상 시스템으로 호스트 머신에서 Kali Linux를 실행하고 있었다. 이 평가를 위한 모든 벤치마크, 도구 및 결과는 추가 웹 페이지에서 사용할 수 있습니다.1

도 1. _FuSeBMC Verification Framework._

[MISSING_PAGE_EMPTY:4]

## References

* (1)
* Azeit(2002) Dave ariel. 2002. advantages of block-based protocol analysis for security testing. _ Immunity Inc., February_105(2002), 106.
* Anghini (1987) Dana Anghini. 1987. Learning regular sets from queries and countererexamples. _ Information and computation_75, 2(1987), 87-106.
* Chanenbaum (2002) A. Tanenbaum. 2002. _컴퓨터 네트워크,th ed_. 프렌티스 홀 전문 기술 참조입니다.
* Barton and James (1990) Barton and et al. James. 1990. Fault injection experiments using FTAI. _ IEEE Trans. Comput._ 39, 4(1990), 575-582).
* 벨라드(2005) F 벨라드. 2005. QEMU, a Fast and Portable Dynamic Translator, USENIX. [http://www.nong.org/qemU/] (http://www.nong.org/qemU/) (2005).
* Black and Bojanova (2016) Paul E Black and Irena Bojanova. 2016. Defeating Buffer Overflow: 작지만 위험한 Bugs. _ IIP professional_18, 6(2016), 58-61.
* Cadar and Cristina (2008) Cadar and et al. Cristina. 2008. KLEE: Unassisted and Automatic Generation of High-Corere Tests for Complex Systems Programs. _OSDI_에 있어서, Vol. 8. 209-224.
* Chiopounov et al(2011) Chiopounov, Vitaly, Volodymyr Kuznetsov, and George Candea. 2011. SZE: A platform for in-vivo multi-path analysis of software systems. _ACM SIGARCH Computer Architecture News_, Vol. 39. ACM, 265-278.
* Chipunov and Vitaly (2009) Chipunov and et al Vitaly. 2009. Selective symbolic execution. _Proceedings of the 5th Workshop on (HotPel)_.
* Cisco(2018) Cisco. 2018. Cisco IDS XE Software Cisco Discovery Protocol Memory Leak Vulnerability. [https://tools.cisco.com/security/center/content/CiscoSecures/Advisory/cisco-s201809206-dcp-mem-trends-c/] (https://tools.cisco.com/security/center/content/CiscoSecures/Advisory/cisco-s201809206-dcp-mem-trends-c/)
* Combs (2018) Gerald Combs. [n.d.]. Wireszk-Goep. [https://www.wireszk.org/] (https://www.wireszk.org/)
* Faria (2008) JP Faria. 2008. Inspections, revision and other techniques of software static analysis. _ 소프트웨어 테스트 및 품질_. _ Feature_9 (2008).
* Gadehla and Cordeiro (2019) Gadehla and et al Cordeiro. 2019. EBMC v6. 0: k-Induction and Invariant Inference를 이용한 C 프로그램 검증. TACAS에 대한 국제 회의입니다. 스프링거, 209-213
* George et al(2016) George, Sherin Mariam, and U.Sangeetha. 2016. Protocol testing with symbolic execution and rule based specification using multicore approach. _ PT_24 (2016), 1609-1615).
* Katsonen et al(2001) Katsonen, Rauli, Marko Laakso, and Ari Takanen. 2001. Software security assessment through specification mutation and fault injection. 새로운 세기의 CMS 이슈들 Springer, 173-183.
* King(1976) James C King. 1976. Symbolic execution and program testing. _ Commun. ACM_19, 7(1976), 385-394.
* Menegers et al(2018) Rafael Menegers, Herbert Rocha, Lucas Cordeiro, and Raimundo Barreto. 2018. MapCheck using LLVM and KLEE. TACAS에 대한 국제 회의입니다. 스프링거, 437-441.
* 위협 백과사전
- Trend Micro USA., 2 페이지 [https://www.trendmicro.com/vinfo/us/threat-encyclopedia/vulnerability/2255/sami-flip-server-user] (https://www.trendmicro.com/vinfo/us/threat-encyclopedia/vulnerability/2255/sami-flip-server-user)
* Mikhail and Cordeiro (2018) Mikhail and et al Cardeiro. 2018. ESBMC 5.0: An Industrial-Strength C Model Checker. In _33rd ACM/IEEE Int. Conf. on (ASE'18)_. ACM, NY, USA, 888-891.
* Miller and Barron (1995) Miller and et al. Barron. 1995. _Inz 재방문 VINK 유틸리티 및 서비스의 신뢰성에 대한 재평가_. 기술 보고서, UW-매디슨
* Munne and Taehiko (2016) Munea and et al Taehiko. 2016. Network protocol fuzz testing for information systems and applications: a survey and taxonomy. _ Multimedia Tools and Applications_75, 22(2016), 1475-1475.
*진 및 리프(2006)진, S, K. 2006. Liff: 보안 공격을 탐지하기 위한 저-오버헤드 실용적인 정보 흐름 추적 시스템. _MICRO'06_에서. IEEE, 135-148.
* Sasanakis and Raimondas (2012) Sasanakis and et al Raimondas. 2012. Integration testing of protocol implementations using symbolic distributed execution. _ICNP_에서. IEEE, 1-6.
* Shamegam and Chao (2016) Wen Shamegam and et al. Feng Chao. 2016. Testing Network Protocol Binary Software with Selective Symplectic Execution. _CIS IEEE_에서, 318-322.
* Song et al(2014) Song, JaeSung, Cristian Cadar, and Peter Pietzuch. 2014. SYMBENNET: testing network protocol implementations with symbolic execution and rule-based specifications. _IEEE_126, 4014) , 695-709.
* Stephens and Giovanni (2016) Stephens and et al Giovanni. 2016. 드릴러: 선택적 상징 실행을 통한 추가 퍼징. _NDS_에서, Vol. 16. 1 내지 16.
* US-CERT (2009) US-CERT. 2009. 서비스 거부 공격 이해 | CISA. [https://www.us-cert.gov/nex/lips/ST04-015] (https://www.us-cert.gov/nex/lips/ST04-015)
* Vanhoef 등(2018) Vanhoef, Mathiy, Piessens, and Frank. 2018. Symbolic execution of security protocol implementations: handling cryptographic primitives. <Izth\(\{\)USENIX\(\}\) Offensive Technologies (\(\{\)WOT\(\}\) 18)_에서.
* Jhajie et al(2013) Wang, Jiaie, Tao Gu, Pulan Zhang, and Qixo Xiao. 2013. A model-based behavioral fuzzing approach for network service. 2013년 IMCCC에 관한 제3차 국제 회의. IEEE, 1129-1134.
* Sun et al(2017) Wen, Shameg, Qingjun Meng, Chao Feng, Chaoying Tang. 2017. Model-guided symbolic execution approach for network protocol implementations and vulnerability detection. _ PloS one_12, 11(2017), e0188229.
* Sun et al(2017) Wan, Shameg, Qingjun Meng, Chao Feng, Chaoying Tang. 2017. Protocol vulnerability detection based on network traffic analysis and binary reverse engineering. _ PloS one_12, 10(2017), e0186188.
* Zalewski (2015) Michal Zalewski. 2015. American Fuzzy Lop(AFL) fuzzer. [http://lamtuf.corredum.co/afl/] (http://lamtuf.corredum.co/afl/)
* Zhang and Zhu (2018) Zhang and et al Zhu. 2018. A new Memory Leak Classification for Evalability of Static Analysis Tools. _2018 IEEE on(PIC)_에서. IEEE, 351-356.
* Zhang and Ting (2017) Li Zhang and Vrijam L. 팅 2017. Hybrid symbolic execution assisted fuzzing method. _TENCON 2017-2017 IEEE Region 10 Conference_에서. IEEE, 822-825.
