# 밀폐 컨테이너의 고온 용융염용 액체 레벨 센서

모하마드 알라자데 1, 로이 D. 마랑고니 2, 마이크 R Lovell 3

1 Hungarian Academy of Sciences Konkoly-Thege ut 29-33 1121 mta-ttk-mfa, Budapest, Hungary, allazadeh@mfa.kfki.hu
2 University of Pittsburgh, 632 Benedum Hall, Pittsburgh, PA 15261, USA maran@engr.pitt.edu
3 University of Wisconsin-Milwaukee, P.O. Box 784, Milwaukee, WI 5320, USA, mlovell@uwm.edu

###### Abstract

용액, 용융염 또는 용융납의 봉재 종류에 따른 전기저항 측정은 유체의 온도(-1000\({}^{\circ}\)C)가 매우 높고 유체의 성질이나 용기의 상태 때문에 기존의 측정이 불가능할 때 밀폐된 용기 내에서 액체 레벨 센서를 설계하기 위해 고려된다. 이 문제에 대한 분석적 해법은 센서의 비용을 줄이고 액체 수준을 예측하기 위해 고온에서 센서의 교정의 어려움을 극복하기 위해 채택된다. 좁은 용기에서 액체에 잠긴 전극봉의 높이 대비 비저항을 계산하기 위한 해석해를 전기회로 모델을 제안하였다. 실험 결과에 대한 회로 모델의 좋은 예측은 액체 용액과 막대 재료의 조합에 대한 해석 결과를 실험 그래프와 비교함으로써 검증된다.

해석 솔루션; 전기 회로 모드; 구속 컨테이너; 고온 액체; 액체 레벨 센서.

## Introduction

직접적인 시각적 측정이 구현될 수 없는 기계 또는 기기에서 액체 높이 레벨에 대한 측정의 요구는 용기 내의 액체 높이의 함수로서 외부 소스에 대한 액체 반응 또는 상이한 물리적, 화학적 또는 기계적 특성의 변동을 사용하여 용기 내의 액체 높이를 나타내도록 교정되는 액체 레벨 센서(LLS)를 설계하려는 동기이다. LLS 장치의 가장 실용적인 방법은 외부 에너지원에 대한 액체의 반응을 측정하는 것이다. 외부 에너지는 초음파 센서에서 사운드 또는 광학 센서에서 광 또는 전기 센서에서 커패시턴스 저항 또는 인덕턴스와 같은 상이한 전기량을 생성하도록 선택될 수 있다.

상부 소스 디바이스 초음파 센서들은 용기 내의 액체의 높이를 결정하기 위해 액체의 레벨로부터 파동의 반사를 채용한다. 바닥 소스 센서의 경우 초음파 센서가 액체를 통해 수신기에 파도에 도달하는 데 필요한 시간이 센서를 보정하는 요인이다.

광학 센서의 주체는 액체 표면으로부터의 광의 반사 또는 내부 전반사(TIR)이다. 후자의 경우, 광섬유가 일상적인 유지를 위해 쉽게 세척된 표면에 매립되는 광섬유 광 유체 센서가 필요하다. 프레넬 방정식은 광섬유 유체 레벨에서 거리를 측정하는 기본적인 도구이다. 광원은 일반 광일 수 있거나, 또는 특별한 적용을 위해, 레이저 또는 적외선 광일 수 있다. 고온에서 치수가 작은 완전히 밀폐된 액체 용기가 필요한 경우 초음파 및 TIR 방법은 모두 적용할 수 없다. 이는 센서의 크기나 구조 및 수신기에 의해 캡처된 정보를 제어하는 데 있어 불확실성에 기인한다.

다른 옵션은 밀도가 다른 다른 액체를 사용하여 액체 위의 압력을 측정하는 방법에 의한 것일 수 있다. 이것은 두 액체를 서로 접촉시켜야 하는데, 이는 두 액체 사이의 유해한 반응으로 인해 많은 경우에 가능하지 않다. 서비스 조건에서 액체 또는 그 구성 요소의 화학적 활성은 제한된 컨테이너에서 일부 액체 이상의 압력 차이를 사용하여 센서의 적용 가능성을 폐기한다.

전기 센서는 액체에 인가된 전압에 응답하여 수집된 정보를 사용하여 액체의 레벨을 결정하는 센서이다. 그들은 LabView와 같은 장치 및 소프트웨어를 제어하기 위해 쉽게 연결할 수 있다는 장점이 있다. 대부분의 일반적이고 간단한 회로에서, 측정가능한 양은 커패시터의 용량, 저항의 저항, 전자장 또는 임피던스에 의한 인덕턴스이며, 여기서 이전 양들의 전부 또는 둘의 조합이 측정가능하다. 그러나, 이들은 전도도 또는 저항률에 기초하여 작동될 수 있다. 전기 전도도는 물질이 전하의 이동을 얼마나 잘 수용하는지 측정하는 모든 물질의 특징이다. 일반적으로 지멘스에서 측정되는 비저항은 전도도의 물리적 의미에 반비례하지만 전도도와 마찬가지로 온도에 따라 달라진다. 현재 대부분의 액체 수위 센서의 기술은 액체 용기 크기, 필요한 액체의 감도 및 작동 온도 등으로 인해 고온에서 모든 유형의 액체의 수위를 측정하기에 적합하지 않다.

본 논문은 화씨 2000도 이상 고온에서 LLS에 사용할 수 있는 기술을 찾고 제안하는 데 초점을 맞추고 있다. 이러한 LLS는 특히 해군에서 사용되는 것과 같은 이동형 및 소형 원자력 발전소에서 많은 산업적 응용을 가지며, 유체의 화학적 활성이 압력차 센서를 사용하는 것을 방지한다. 현재 실험의 목표는 폭이 0.625인치 미만인 용기에 갇힌 뜨거운 액체의 수준을 측정하는 적절하고 쉬운 방법을 찾는 것이다. 대물 유체는 공기 및 수분에 노출될 수 없는 FLiNaK(0.465 LiF, 0.115 NaF, 및 0.42 KF)를 용융하므로, 용기의 구속 완료는 필수적인 요건이다. 따라서 FLiNaK 유체는 산업 적용을 위해 내화성 금속 밀봉 용기에 채워져야 하며, 이는 용기의 액체 높이를 결정하기 위해 설명된 센서 중 가능한 옵션을 좁힌다. 표면 또는 내부 반사 주체로 작동하는 초음파 센서용 액체 및 광학 센서용 얕은 용기의 표면에서 소리를 반사할 때 가능한 기생충 음파 신호뿐만 아니라 간단한 방법과 문제의 비용 효과를 추구하여 전기 센서를 쉽고 저렴하고 실용화할 수 있다. 본 논문은 좁은 용기에 수용된 액체에 잠긴 전극봉의 높이에 대한 전기 저항을 계산하기 위한 해석적 해를 위한 전기 회로 모델을 소개한다.

### 실험'설명 및 결과'

실험 세트의 수는 막대 재료와 용액의 다양한 조합으로 수행되었다. 로드는 테스트-2 용기 위에 서로 특정 거리를 두고 장착되었으며 그 사이에 전압이 유지되었다. 미리 정의된 경과 시간에 액체 용액의 특정 부분을 용기에 첨가하였다. 디지털 LCR을 사용하여 두 막대 사이의 전기 저항을 측정했다. 그림 1은 이러한 실험의 일반적인 관점을 제공한다. 테스트-2 용기는 500ml 스케일의 플라스틱이 떨어졌다. 본 실험에 사용된 LCR 장치는 HIOKI 브랜드 모델 3511-50 LCR HiTE로 고속 측정 및 정밀도가 \(\pm\)0.08%로 높게 측정되었다. LCR 미터는 9140개의 단자 프로브로 막대에 연결되었다. 설치된 LCR 미터는 표 1에 나열되어 있다. 로드 사이의 거리는 두 개 또는 세 개의 스페이서를 통해 로드를 따라 일정하게 유지되어 로드가 평행하게 유지된다. 막대는 실험 중 움직임을 피하고 수직 방향으로 똑바로 유지하기 위해 용기에 대해 고정되었다. LCR 미터는 두 개의 단자 프로브로 막대에 연결되었다. 이는 도 2에서 확인할 수 있다.

로드에 있는 프로브의 위치는 로드의 높이를 달리하여 연결하여 실험 결과에 비효율적인 것으로 조사되었다. 플라스틱 파이프에 부착된 깔때기를 사용하여 정확한 측정을 위한 테스트 동안 막대의 젖음을 피하기 위해 새로운 부분의 액체를 용기에 붓는다. 를 포함하며,

도 2: 로드에 대한 프로브의 연결

[MISSING_PAGE_FAIL:3]

### 실험 집합 3. Rods' 직경

이 실험에서 막대 직경이 결과에 미치는 영향은 NaF 용액 전해질과 세 가지 다른 직경을 가진 전극으로 쌍 몰리브덴 막대를 사용하여 조사된다. 막대는 직경이 0.050, 0.080 및 0.125인치인 약 3피트 길이였다. 리코딩 데이터는 0.05 및 0.08의 막대의 경우 0.1인치, 0.125인치 직경의 경우 0.2인치 직경의 다음 높이 수준에서 시작되었다. 경사각이 0is보다 충분히 큰 그래프의 단면은 액체 레벨에서 봉의 비저항과 높이 사이에 일대일 대응하는 값을 찾기 위해 고려된다. 이 섹션은 그래프의 _보정 줌_ 으로 레이블을 지정할 수 있습니다. 그림 7로부터 막대의 직경이 감소함에 따라 그래프의 교정 줌이 크게 넓어진다는 결론을 내릴 수 있다.

### 실험 테스트 4. 로드 분리 거리

실험 세트-3과 동일한 실험 조건이지만 막대 사이의 간격이 다른 몰리브덴 막대를 사용하여 직경 0.5인치 3피트 길이의 몰리브덴 막대가 두 막대 사이의 간격이 두 막대 사이에 측정된 저항에 영향을 미치는지 여부를 조사했다. 그림 8은 120Hz 주파수에 대해 막대 사이의 0.25, 0.5 1 및 1.5인치 간격으로 실험한 결과에 대한 그래프이다.

더 높은 막대의 공간에서 저항이 더 커지는 것을 관찰할 수 있다. 이는 액체 내에서 전류에 대한 통과 경로가 증가되는 로드들 사이의 액체의 양을 증가시킴으로써 설명될 수 있다. 이러한 경로의 증가는 막대기 사이의 액체의 양에 대한 저항 함수인 저항률을 갖는다. 또한 그림 8은 전기비저항 상승이 미미하고 액체 수준의 6인치 미만의 교정 영역에만 속한다는 것을 보여준다.

### 실험 집합 5. Rods' Material

봉의 저항은 두 봉 사이의 저항에 중요한 역할을 한다. 이 실험은 봉의 재료가 같은 액체 용액에 잠긴 다른 재료에서 봉 사이의 전기 저항에 미치는 영향을 수행하고 잠긴 봉의 높이 대 모델의 저항을 그래프로 비교한다.

도 5 : 금속 콘테이너 효과 검사용 실험 구조

도 6: 금속제제가 결과에 미치는 영향을 조사하기 위한 실험세트 2와 3의 비교

도 7: NAF SOLUTION에서 상이한 DIAMETER SUMMERGED를 갖는 몰리브덴 ROS의 저항 VERSUS HEIGHT 비교 도 9는 불화물 나트륨에서 직경 0.14 인치를 갖는 강봉과 0.125 인치를 갖는 몰리브덴 둘 다의 비교를 나타낸다. 직경의 차이가 미미함에도 불구하고 F-Na 용액에서도 유사하게 행동하며 막대 사이에 50mV 전압을 사용한다. 이는 금속 310의 전도도가 1.3x 10\({}^{4}\) S이고 몰리브덴의 전도도가 19x 10\({}^{4}\) S인 원인일 수 있다. 봉 전도도의 효과는 금속봉(전도도가 훨씬 높은)을 탄화규소와 같은 반도체와 비교하면 더 명백하다. 그림 10은 물에서 SiC와 강철 막대의 비교를 보여주는 반면, 그림 11은 F-Na 수용액에서 0.14인치 직경 강철과 0.125인치 직경 몰리브덴 막대가 있는 0.25인치 직경 SiC 막대의 비교이다. 그림 12의 그래프에서 양호한 전도성 금속 막대에 비해 액체 수준의 모든 범위에 대해 낮은 전도성 SiC 막대 사이에서 저항률이 높다는 것을 알 수 있다.

## Discussion

고온에서 재료의 열적 특성은 충분히 알려져 있지 않으므로 이러한 모든 데이터는 외삽에 의해 제공되어야 한다. 이러한 특성의 비선형 거동은 이러한 외삽을 다소 신뢰할 수 없게 만든다. 재료의 전도도 및 비저항은 온도에 따라 달라지며 결과적으로 고온에서의 열적 특성 거동에 영향을 받는 재료 특성이다. 재료의 전도도는 많은 원소 및 엔지니어링 재료에 대해 확립되어 왔으며 온도가 증가함에 따라 재료의 전도도가 감소하거나 일부 다른 재료에서는 더 높은 온도에서 비저항이 증가하여 나타나는 것으로 잘 알려져 있다. 원자 격자 구조에서 불완전성의 증가는 전자 이동을 방해한다. 또한 열에너지는 원자의 평형 위치에 대한 진동을 유발하여 전자 이동을 방해한다. 따라서, 액체 레벨 센서의 교정을 용이하게 하기 위해 사용될 수 있는 모델을 갖는 것은 고온에서의 센서의 교정의 어려움(예를 들어, 안전 문제, 비용 효과, 필요한 장비, 시간 등)을 감소시킨다. 실험 집합의 결과를 요약하면 적절한 분석 모델을 수립하는 데 도움이 된다.

상온에서 DC 전압차를 받는 두 개의 로드 사이에서 측정된 저항에 대한 실험 세트 결과의 요약에 다음의 코멘트가 나열될 수 있고,

액체 레벨에서 로드의 높이를 증가시키면 물에서의 저항과 물 용액에서의 F-Na 모두 감소하는데, 이는 그림 3과 4에서 볼 수 있다. 이는 실질적으로 절연체인 공기에 비해 액체의 전도도가 높기 때문이다. 따라서 액체로 채워진 막대 사이의 간격이 클수록 양극에서 음극으로의 전자의 이동이 쉬워진다. 여기서, 전자의 이동 방향에 대해서는 종래의 부호가 고려된다.

액체 전도도가 저항에 미치는 영향은 그림 4에서 분명하다.

그림 6의 그래프를 비교하면 두 막대 사이의 간격만이 전기 저항에 영향을 미치고 용기 공간은 측정된 저항에 미치는 영향이 미미함을 알 수 있다.

Rod의 직경은 교정 영역에서 저항과 반비례 관계를 갖는다. 그림 7에서 직경이 다른 다른 몰리브덴 막대에 대한 그래프는 동일한 실험 조건에 대해 더 두꺼운 막대가 더 적은 저항을 갖는다는 것을 보여준다.

막대 사이의 공간은 저항과 직접적인 관계를 가지며, 이는 그림 8의 그래프를 통해 확인된다.

동일한 액체에 대해 그래프의 모양은 막대의 전도도에 따라 달라진다. 이 사실은 그림 9, 10, 11에서 결론을 내린다.

앞서 언급한 요약에서 측정된 저항에 대한 요인의 효과는 액체 레벨 센서의 저항 기반 기술이 전기 회로로 모델링될 수 있음을 시사하며, 이는 다음 섹션에서 설명된다.

그리고, 재료 저항률을 다음으로서 이용함으로써 막대와 액체에 대한 재료의 저항을 얻을 수 있고,

\[R_{1}=\frac{\rho_{liquid}L_{liquid}}{A_{L}}\] (Eq-1)

\[R_{2}=R_{3}=\frac{\rho_{rad}(L_{rad}-y)}{A_{red}}\] (Eq-2)

여기서, \(y\)는 액체에 잠긴 막대의 높이이다. 액체의 비저항은 \(\rho_{liquid}\)이며, 그 값은 FLiNaK의 전기전도도와 같다. \ (\rho_{rad}\)는 실험에 사용된 봉의 전기비저항이다. \ (L_{liquid}\)는 R1에 대해 고려된 저항의 길이이며 두 막대 사이의 액체의 저항과 같다(그림 12의 h). 봉의 단면적은 \(A_{rad}=\pi\)\(d_{rad}/A_{L}\)으로 총 저항에서 유효 전기저항을 근사하는 두 봉 사이의 액체 영역이다. 2차원 모델에서 \(A_{L}\)은

[MISSING_PAGE_FAIL:7]

[MISSING_PAGE_EMPTY:8]

[MISSING_PAGE_FAIL:9]

제안된 회로 모델을 사용하여 막대 및 막대 직경 사이의 공간에 대한 영향을 해석적으로 재조사하면 실험적으로 주장된 것과 동일한 결론을 얻을 수 있다. 이 결과는 그림 26과 27의 비교를 통해 얻을 수 있다. 그림 28은 Eq-3의 분석 모델을 기반으로 한 용융 납 용액에서 h=1.0 인치의 0.25인치 직경의 탄화규소 막대의 선형 응답을 보여준다. 결과적으로 이 모델은 모든 실험, 다른 재료의 막대 및 액체 용액에 일반적인 의미로 사용되어 다양한 용도와 응용에 대한 다양한 유형의 액체 레벨 센서를 생성할 수 있다.

## Conclusions

비저항 기반 전기 센서는 특히 화학 반응성 때문에 유체가 임의의 다른 유체 또는 기체와 접촉할 수 없을 때, 또는 종래의 유형의 LLS가 용기의 상황으로 인해 기능하지 못할 때 폐쇄 루프 또는 밀봉된 용기 내의 고온에서 LLS를 설계하는데 있어서 정확하고 적합한 선택이다. 비저항 기반 레벨 센서는 측정된 저항에 기초하여 유체 레벨이 결정되는 간단한 설계를 갖는다. 해석적 계산을 위해 전기 회로 모델이 제안되고 검증되었다. 실험 결과는 해석식의 타당성을 확인하였다. 다양한 요인이 측정된 저항에 영향을 미치므로 이러한 센서는 정확하게 보정되어야 한다. 실험 결과와 분석 결과는 이러한 요인의 영향을 다음과 같이 승인한다.

상기 로드들 사이의 공간은 측정된 저항을 증가시키고,

로드의 직경은 저항값과 반비례 관계를 가지며,

로드의 전기 저항률은 기록된 저항과 직접적인 관계를 가지며,

액체의 비저항은 센서의 전기 저항을 증가시키고,

액체 레벨은 액체에 잠긴 막대의 높이에 의해 결정된다. 액위 증가에 따라 저항이 감소하고,

저항 대 액체 레벨 그래프는 액체와 비교하여 막대의 전도도 간의 차이에 따라 달라진다. 봉이 전도성을 기준으로 분류되면 그래프는 지수함수이고 절연체로 표시되면 그래프는 선형이다.

액체 수위 센서 및 이 방법을 설계하는 방법

도 28: 리드솔루션에서의 실리콘 카바이드에 대한 해석적 결과

도 26: 로드 사이의 간격이 저항 분석에 미치는 영향 조사

제안된 해석 모델은 고온에서 광범위한 산업 응용 분야에 적용될 수 있다.

## References

* Balbuena(1999) Balbuena, Perla B., Conductivity and viscosity studies of ethylene carbonate based solution containing lithium perchlorate, Prabhu, P.V.S.S. (Central Electrical Carolina), Journal of the Electrochemical Society, v 146, n 10, Oct, 1999, p 3613-3622
* Boca Raton (1985) Boca Raton, CRS Handbook of Chemistry and Physics, 66\({}^{\text{\text{\tiny{th}}}}\) edition, CRC Press, Inc., Florida, pp. B-68-b-161 (1985)
* Chen et al. (2000) Chen, H.P., Fregus J.W., Jang, B.Z., Effect of Ethylene carbonate and salt concentration on the conductivity of propolyene carbonate/lithium percholate electrolytes, Journal of the electrochemical Society, v 147, n 2, Feb, 200, p 339-406
* J. Janz (1992) G J. Janz, NIST Standard database 27, NIST Properties of melting Salt database, version 2.0 Molten salts Data Center, Rensselaer Polytechnic Institute, Trot, NY, NIST, (1992) distributed by NIST, (1992).
* J. W Snow (1988) J. W Snow, A fiber optic fluid level sensor; Practical 고려사항 SPIE Vol 945 optical testing and Metrology II (1988), 657-661
* J. Barthel and R Buchner (1995) J. Barthel, R Buchner, Chemistry Data Series, Vol. XII, Part 2, Water and aqueous electrolyte solution, ISBN 3-926959-62-2, 1995
* J. Barthel and R. Buchner (1995) J. Barthel, R. 부흐너 Munsterer, 물과 수용액 전해액의 유전 특성, 화학 데이터 시리즈, Vol. XII 파트 2, ISBN 3-926959-62-2,1995
* J. Barthel and R. Neueder (1996) J. Barthel, R. 비양성자성,영양성 용매 용액의 Neueder, Conductivity, Transference Number, Limiting Ionic Conductivity II: Carbonates, Electrolyte data collection, Chemistry data series, Vol. XII, Part 1d
* J. Barthel and R. Neueder (1996) J. Barthel, R. 비양성자성, 영양성 용매 IV 케톤, 에스테르 및 니트로하이드로카본, 전해질 데이터 수집,
* Li et al. (1999) Li, Tao, Balbuena, Perla B., Theoretical studies of lithium percholate in ethylene carbonate, propylene carbonate, ant their mixtures, Journal of Electrochemical society, v 146, n 10, Oct, 1999, p 3613-362
